### ISSUE TITLE
New ExpressionSet does not support sparse matrix?

### ISSUE THREAD

**Issue by qinzhu** [Bioconductor/Biobase#21]
Hi, 
I noticed there has been an update on the biobase. It appears now when I try to create an expressionSet with sparse matrix I get following error:
```
obj <- new("ExpressionSet", exprs = exprs(eset)) # exprs(eset) was a sparse matrix from an old eset object
Error: unable to find an inherited method for function ‘annotatedDataFrameFrom’ for signature ‘object = "dgCMatrix"’
```
So what is the recommended approach now for dealing with large sparse data matrix with ExpressionSet class?

**Comment by mtmorgan** [comment]
One work-around is to provide phenoData and featureData directly
```
obj <- new("ExpressionSet", exprs =  exprs(eset), phenoData = phenoData(eset), featureData = featureData(est))
```
Note that one usually creates objects with their constructor `ExpressionSet(...)` rather than invoking `new()` directly. However, `ExpressionSet()` seems only to support sparse matrices.

Note also that the [SummarizedExperiment][] package and class (or derived classes, e.g., SingleCellExperiment) offer a more modern and supported eset-like class.

[SummarizedExperiment]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by qinzhu** [comment]
Thanks for the quick response, the code works. "However, ExpressionSet() seems only to support sparse matrices." I think you mean it does not support sparse matrices?
I tried code below:
```
counts= exprs(eset)
pmeta = pData(eset)
fmeta = fData(eset)
obj = ExpressionSet(
    assayData = assayDataNew( "environment", exprs=counts),
    phenoData = new("AnnotatedDataFrame", data = pmeta),
    featureData = new("AnnotatedDataFrame", data = fmeta)
)
```
The error persist, but 
```
obj = new("ExpressionSet", 
    assayData = assayDataNew( "environment", exprs=counts),
    phenoData = new("AnnotatedDataFrame", data = pmeta),
    featureData = new("AnnotatedDataFrame", data = fmeta)
)
```
has no error.
Anyway, thanks for the help!
